---
name: Checks

on: [push] # Trigger on push events

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER  }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
  # - name: Lint
  #   run: docker compose run --rm app sh -c "flake8"  # comment this because there was an error in the code
